import './global.css';
import Header from '../components/Header';

export const metadata = {
    title: 'Time Tracker',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />

                <main className="">{children}</main>

                <footer className="text-gray-400 text-center text-xs py-5">
                    <p>github.com/nunomh - 2024</p>
                </footer>
            </body>
        </html>
    );
}
