import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>Time Tracker App</header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
